apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-selector"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-selector"
        version: "current"
    spec:
      containers:
      - name: "{{ .Release.Name }}"
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        command: ["node"]
        args: [ "{{ .Values.path }}" ]
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
