name: Terraform apply
on:
  push:
    branches: [ main ]
jobs:
  diff:
    runs-on: ['self-hosted']
    name: diff
    outputs:
      diff: ${{ steps.diff.outputs.all_changed_and_modified_files }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Diff
      id: diff
      uses: tj-actions/changed-files@v16
  apply:
    runs-on: ['self-hosted', 'X64']
    name: apply
    needs: diff
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_project_name: ${{ github.repository }}
      TF_VAR_scw_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_scw_private_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_scw_project_id: 04c90b28-9bd5-4a90-b18c-6b8ec5cb5f3a
    steps:
    - name: Apply platform
      # if: contains(needs.diff.outputs.diff, 'iac/terraform/platform')
      uses: dflook/terraform-apply@v1
      with:
        path: iac/terraform/platform
        auto_approve: true
    # - name: Get kubeconfig
    #   uses: dflook/terraform-apply@v1
    #   with:
    #     path: iac/terraform/kubeconfig
    #     auto_approve: true
    - name: Apply services
      # if: contains(needs.diff.outputs.diff, 'iac/terraform/services')
      uses: dflook/terraform-apply@v1
      with:
        path: iac/terraform/services
        auto_approve: true
    - name: Apply algorithms
      # if: contains(needs.diff.outputs.diff, 'iac/terraform/algorithms')
      uses: dflook/terraform-apply@v1
      with:
        path: iac/terraform/algorithms
        auto_approve: true
