name: Terraform plan
on:
  pull_request:
    branches: [ main ]
jobs:
  plan:
    runs-on: ['self-hosted', 'X64']
    name: plan
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: terraform plan
      uses: dflook/terraform-plan@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_VAR_project_name: ${{ github.repository }}
        TF_VAR_scw_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_scw_private_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_scw_project_id: 04c90b28-9bd5-4a90-b18c-6b8ec5cb5f3a
      with:
        path: iac/terraform
