name: Terraform plan
on:
  pull_request:
    branches: [ main ]
jobs:
  plan:
    runs-on: ['self-hosted', 'X64']
    name: plan
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_project_name: ${{ github.repository }}
      TF_VAR_scw_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_scw_private_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_scw_project_id: 04c90b28-9bd5-4a90-b18c-6b8ec5cb5f3a
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Plan platform
      uses: dflook/terraform-plan@v1
      with:
        path: iac/terraform/platform
    - name: Get kubeconfig
      uses: dflook/terraform-apply@v1
      with:
        path: iac/terraform/kubeconfig
    - name: Check kubeconfig exists
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "./iac/terraform/config_hashcode"
    - name: Plan services
      if: steps.check_files.outputs.files_exists == 'true'
      uses: dflook/terraform-plan@v1
      with:
        path: iac/terraform/services
